config/routes.rb
Rails.application.routes.draw do

  resources :admins
  resources :rentals do
    resources :reservations
  end
  get 'home/index'
  root :to => "home#index"

  get 'apibooking/',to: 'apibooking#getRentalAll'
  get 'apibooking/getRentalAll',to: 'apibooking#getRentalAll'
  get 'apibooking/getRental/:id',to: 'apibooking#getRental'
  get 'apibooking/index/:id', to: 'apibooking#index'
  get 'apibooking/delRental/:id', to: 'apibooking#delRental'
  match 'apibooking/addRental', to: 'apibooking#addRental', via: [:get, :post] #:rental_params

  get 'apibooking/:rental_id/delReservation/:reserv_id',to: 'apibooking#delReservation'
  get 'apibooking/:id/getReservations',to: 'apibooking#getReservations'
  match 'apibooking/addReservation', to: 'apibooking#addReservation', via: [:get, :post] #:reservation_params,:rental_id

  match 'apibooking/getAdmins' => 'apibooking#getAdmins', via: [:get, :post]
  match 'apibooking/checkAdmin' => 'apibooking#checkAdmin', via: [:get, :post]  #:email , :password

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental < ApplicationRecord
  validates :name,  :presence => true
  validates :address, :presence => true,
            :length => { :minimum => 5 }

  has_many :reservations, :dependent => :destroy
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:name, :address, :description, :photo, :daily_rate)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental, local: true) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :rental_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :rental_address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :rental_description %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :rental_photo %>
  </div>

  <div class="field">
    <%= form.label :daily_rate %>
    <%= form.text_field :daily_rate, id: :rental_daily_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Photo</th>
      <th>Daily rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.name %></td>
        <td><%= rental.address %></td>
        <td><%= rental.description %></td>
        <td><%= rental.photo %></td>
        <td><%= rental.daily_rate %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rental.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @rental.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rental.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @rental.photo %>
</p>

<p>
  <strong>Daily rate:</strong>
  <%= @rental.daily_rate %>
</p>

<h2>Reservations</h2>
<%= render @rental.reservations %>

<h2>Add a Reservation:</h2>
<%= render "reservations/form" %>

<br />

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>