config/routes.rb
Rails.application.routes.draw do

  resources :admins
  resources :rentals do
    resources :reservations
  end
  get 'home/index'
  root :to => "home#index"

  get 'apibooking/',to: 'apibooking#getRentalAll'
  get 'apibooking/getRentalAll',to: 'apibooking#getRentalAll'
  get 'apibooking/getRental/:id',to: 'apibooking#getRental'
  get 'apibooking/index/:id', to: 'apibooking#index'
  get 'apibooking/delRental/:id', to: 'apibooking#delRental'
  match 'apibooking/addRental', to: 'apibooking#addRental', via: [:get, :post] #:rental_params

  get 'apibooking/:rental_id/delReservation/:reserv_id',to: 'apibooking#delReservation'
  get 'apibooking/:id/getReservations',to: 'apibooking#getReservations'
  match 'apibooking/addReservation', to: 'apibooking#addReservation', via: [:get, :post] #:reservation_params,:rental_id

  match 'apibooking/getAdmins' => 'apibooking#getAdmins', via: [:get, :post]
  match 'apibooking/checkAdmin' => 'apibooking#checkAdmin', via: [:get, :post]  #:email , :password

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :rental
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create_back
    @rental = Rental.find(params[:rental_id])
    @reservation = @rental.reservations.create(params[:reservation])
    redirect_to rental_path(@rental)
  end
  def destroy
    @rental = Rental.find(params[:rental_id])
    @reservation = @rental.reservations.find(params[:id])
    @reservation.destroy
    redirect_to rental_path(@rental)
  end

  def create
    @rental = Rental.find(params[:rental_id])
    @reservation = @rental.reservations.new(reservation_params)

    if @reservation.save
      #redirect_to :action => 'list'
      redirect_to rental_path(@rental)
    else
      @rentals = Rental.all
      render :action => 'new'
    end
  end

  def reservation_params
    params.require(:reservation).permit(:client_email, :start_at, :end_at)
  end


  def list
    @reservations = Reservation.all
  end

  def show
    @reservation = Book.find(params[:id])
  end

  def new
    @reservation = Reservation.new
    @rentals = Rental.all
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for([@rental, @rental.reservations.build]) do |form| %>

  <div class="field">
    <%= form.label :client_email %>
    <%= form.text_field :client_email, id: :reservation_client_email %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.date_select :start_at, id: :reservation_start_at %>
  </div>

  <div class="field">
    <%= form.label :end_at %>
    <%= form.date_select :end_at, id: :reservation_end_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<p>
  <b>Client email:</b>
  <%= reservation.client_email %>
</p>

<p>
  <b>start date:</b>
  <%= reservation.start_at %>
</p>

<p>
  <b>end date:</b>
  <%= reservation.end_at %>
</p>

<p>
  <%= link_to 'Destroy Reservation', [reservation.rental, reservation],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Client email</th>
      <th>Start at</th>
      <th>End at</th>
      <th>Rental</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.client_email %></td>
        <td><%= reservation.start_at %></td>
        <td><%= reservation.end_at %></td>
        <td><%= reservation.rental %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client email:</strong>
  <%= @reservation.client_email %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @reservation.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @reservation.end_at %>
</p>

<p>
  <strong>Rental:</strong>
  <%= @reservation.rental %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>